--------------------------------------------------------
-- Archivo creado  - viernes-mayo-17-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAMPAIGN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CAMPAIGN" 
   (	"ID_CAMPAIGN" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(250 BYTE), 
	"APELLIDOS" VARCHAR2(250 BYTE), 
	"TELEFONOS" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CAMPAIGN_INDEX1
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."CAMPAIGN_INDEX1" ON "SYSTEM"."CAMPAIGN" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
